/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import donnée.Bdd;
import java.net.URL;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import métier.Categories;
import métier.Planning;

/**
 *
 * @author etien
 */
public class AccueilFDC extends javax.swing.JFrame {
    
    private static Connection conn = Bdd.coBdd();
   
    
    private static String[][] CategorieNonPlanifié = Categories.recupCatDispo();
    private static String[][] tabPlanning = Planning.recupPlanning();
    
    private static int idCatDispoSelectionné;
    
    /**
     * Creates new form FDC
     */
    public AccueilFDC() {
        initComponents();
        URL iconURL = getClass().getResource("/vue/LogoFDC.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        jDialogPasDePlanning.setIconImage(icon.getImage());
        jDialogPasDePlanning.setLocationRelativeTo(this);
        jDialogSelectionAfficherPlanning.setIconImage(icon.getImage());
        jDialogSelectionAfficherPlanning.setLocationRelativeTo(this);
        jDialogSelectionCréactionPlanning.setIconImage(icon.getImage());
        jDialogSelectionCréactionPlanning.setLocationRelativeTo(this);
        jDialogSelectionModifierPlanning.setIconImage(icon.getImage());
        jDialogSelectionModifierPlanning.setLocationRelativeTo(this);
        jDialogSelectionSuppPlanning.setIconImage(icon.getImage());
        jDialogSelectionSuppPlanning.setLocationRelativeTo(this);
        jDialogTropDePlanning.setIconImage(icon.getImage());
        jDialogTropDePlanning.setLocationRelativeTo(this);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        erreurDeConnexionBdd = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDialogPasDePlanning = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDialogSelectionCréactionPlanning = new javax.swing.JDialog();
        listCatDispo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDialogSelectionSuppPlanning = new javax.swing.JDialog();
        listPlanningDispo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bAnnuler = new javax.swing.JButton();
        bSupprimer = new javax.swing.JButton();
        jDialogSelectionAfficherPlanning = new javax.swing.JDialog();
        listPlanningDispo_Affichage = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jDialogSelectionModifierPlanning = new javax.swing.JDialog();
        listPlanningDispo_Modif = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jDialogTropDePlanning = new javax.swing.JDialog();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bConsulterPlanning = new javax.swing.JButton();
        bModifierPlanning = new javax.swing.JButton();
        bCréerPlanning = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bSuppPlanning = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        erreurDeConnexionBdd.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        erreurDeConnexionBdd.setTitle("Erreur de connexion à la BDD");
        erreurDeConnexionBdd.setAlwaysOnTop(true);
        erreurDeConnexionBdd.setMinimumSize(new java.awt.Dimension(403, 247));
        erreurDeConnexionBdd.setResizable(false);
        erreurDeConnexionBdd.setSize(new java.awt.Dimension(403, 247));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Quitter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Erreur de connexion à la BDD");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout erreurDeConnexionBddLayout = new javax.swing.GroupLayout(erreurDeConnexionBdd.getContentPane());
        erreurDeConnexionBdd.getContentPane().setLayout(erreurDeConnexionBddLayout);
        erreurDeConnexionBddLayout.setHorizontalGroup(
            erreurDeConnexionBddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(erreurDeConnexionBddLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        erreurDeConnexionBddLayout.setVerticalGroup(
            erreurDeConnexionBddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erreurDeConnexionBddLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Aucun planning n'est créé, vous devez en créer un !");

        javax.swing.GroupLayout jDialogPasDePlanningLayout = new javax.swing.GroupLayout(jDialogPasDePlanning.getContentPane());
        jDialogPasDePlanning.getContentPane().setLayout(jDialogPasDePlanningLayout);
        jDialogPasDePlanningLayout.setHorizontalGroup(
            jDialogPasDePlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogPasDePlanningLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(46, 46, 46))
            .addGroup(jDialogPasDePlanningLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogPasDePlanningLayout.setVerticalGroup(
            jDialogPasDePlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogPasDePlanningLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addGap(78, 78, 78)
                .addComponent(jButton6)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jDialogSelectionCréactionPlanning.setTitle("Créaction d'un planning");
        jDialogSelectionCréactionPlanning.setResizable(false);
        jDialogSelectionCréactionPlanning.setSize(new java.awt.Dimension(525, 206));

        listCatDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCatDispoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Créaction d'un planning");

        jLabel5.setText("Type de Planning :");

        jButton1.setText("Création Manuel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Création automatique");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSelectionCréactionPlanningLayout = new javax.swing.GroupLayout(jDialogSelectionCréactionPlanning.getContentPane());
        jDialogSelectionCréactionPlanning.getContentPane().setLayout(jDialogSelectionCréactionPlanningLayout);
        jDialogSelectionCréactionPlanningLayout.setHorizontalGroup(
            jDialogSelectionCréactionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSelectionCréactionPlanningLayout.createSequentialGroup()
                .addGroup(jDialogSelectionCréactionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSelectionCréactionPlanningLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel4))
                    .addGroup(jDialogSelectionCréactionPlanningLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jDialogSelectionCréactionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDialogSelectionCréactionPlanningLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listCatDispo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogSelectionCréactionPlanningLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jDialogSelectionCréactionPlanningLayout.setVerticalGroup(
            jDialogSelectionCréactionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSelectionCréactionPlanningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(jDialogSelectionCréactionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listCatDispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jDialogSelectionCréactionPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jDialogSelectionSuppPlanning.setTitle("Suppression d'un planning");
        jDialogSelectionSuppPlanning.setResizable(false);
        jDialogSelectionSuppPlanning.setSize(new java.awt.Dimension(525, 206));

        listPlanningDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPlanningDispoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Suppression d'un planning");

        jLabel7.setText("Séléctionner un planning :");

        bAnnuler.setText("Annuler");
        bAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnulerActionPerformed(evt);
            }
        });

        bSupprimer.setText("Supprimer");
        bSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSelectionSuppPlanningLayout = new javax.swing.GroupLayout(jDialogSelectionSuppPlanning.getContentPane());
        jDialogSelectionSuppPlanning.getContentPane().setLayout(jDialogSelectionSuppPlanningLayout);
        jDialogSelectionSuppPlanningLayout.setHorizontalGroup(
            jDialogSelectionSuppPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSelectionSuppPlanningLayout.createSequentialGroup()
                .addGroup(jDialogSelectionSuppPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSelectionSuppPlanningLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel6))
                    .addGroup(jDialogSelectionSuppPlanningLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listPlanningDispo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogSelectionSuppPlanningLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(bAnnuler)
                        .addGap(83, 83, 83)
                        .addComponent(bSupprimer)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jDialogSelectionSuppPlanningLayout.setVerticalGroup(
            jDialogSelectionSuppPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSelectionSuppPlanningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addGroup(jDialogSelectionSuppPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPlanningDispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jDialogSelectionSuppPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAnnuler)
                    .addComponent(bSupprimer))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        int j = 0;
        tabPlanning = Planning.recupPlanning();
        while (tabPlanning[j][1] != null && j < tabPlanning.length){
            listPlanningDispo.addItem(tabPlanning[j][0]);
            j++;
        }

        jDialogSelectionAfficherPlanning.setTitle("Affichage d'un planning");
        jDialogSelectionAfficherPlanning.setResizable(false);
        jDialogSelectionAfficherPlanning.setSize(new java.awt.Dimension(525, 206));

        listPlanningDispo_Affichage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPlanningDispo_AffichageActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Affichage d'un planning");

        jLabel9.setText("Type de Planning :");

        jButton3.setText("Valider");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSelectionAfficherPlanningLayout = new javax.swing.GroupLayout(jDialogSelectionAfficherPlanning.getContentPane());
        jDialogSelectionAfficherPlanning.getContentPane().setLayout(jDialogSelectionAfficherPlanningLayout);
        jDialogSelectionAfficherPlanningLayout.setHorizontalGroup(
            jDialogSelectionAfficherPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSelectionAfficherPlanningLayout.createSequentialGroup()
                .addGroup(jDialogSelectionAfficherPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSelectionAfficherPlanningLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel8))
                    .addGroup(jDialogSelectionAfficherPlanningLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listPlanningDispo_Affichage, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSelectionAfficherPlanningLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(226, 226, 226))
        );
        jDialogSelectionAfficherPlanningLayout.setVerticalGroup(
            jDialogSelectionAfficherPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSelectionAfficherPlanningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addGroup(jDialogSelectionAfficherPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPlanningDispo_Affichage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(45, 45, 45))
        );

        int i2 = 0;
        tabPlanning = Planning.recupPlanning();
        while (tabPlanning[i2][1] != null && i2 < tabPlanning.length){
            listPlanningDispo_Affichage.addItem(tabPlanning[i2][0]);
            i2++;
        }

        jDialogSelectionModifierPlanning.setTitle("Modifier un planning");
        jDialogSelectionModifierPlanning.setResizable(false);
        jDialogSelectionModifierPlanning.setSize(new java.awt.Dimension(525, 206));

        listPlanningDispo_Modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPlanningDispo_ModifActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Modifier un planning");

        jLabel11.setText("Type de Planning :");

        jButton4.setText("Valider");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSelectionModifierPlanningLayout = new javax.swing.GroupLayout(jDialogSelectionModifierPlanning.getContentPane());
        jDialogSelectionModifierPlanning.getContentPane().setLayout(jDialogSelectionModifierPlanningLayout);
        jDialogSelectionModifierPlanningLayout.setHorizontalGroup(
            jDialogSelectionModifierPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSelectionModifierPlanningLayout.createSequentialGroup()
                .addGroup(jDialogSelectionModifierPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSelectionModifierPlanningLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel10))
                    .addGroup(jDialogSelectionModifierPlanningLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listPlanningDispo_Modif, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogSelectionModifierPlanningLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(226, 226, 226))
        );
        jDialogSelectionModifierPlanningLayout.setVerticalGroup(
            jDialogSelectionModifierPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSelectionModifierPlanningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(35, 35, 35)
                .addGroup(jDialogSelectionModifierPlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPlanningDispo_Modif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(45, 45, 45))
        );

        int i3 = 0;
        tabPlanning = Planning.recupPlanning();
        while (tabPlanning[i3][1] != null && i3 < tabPlanning.length){
            listPlanningDispo_Affichage.addItem(tabPlanning[i3][0]);
            i3++;
        }

        jDialogTropDePlanning.setTitle("ATT : Tous les plannings sont déja créés !");
        jDialogTropDePlanning.setPreferredSize(new java.awt.Dimension(370, 300));
        jDialogTropDePlanning.setResizable(false);
        jDialogTropDePlanning.setSize(new java.awt.Dimension(400, 230));

        jButton7.setText("OK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Tous les plannings sont déja créés !");

        javax.swing.GroupLayout jDialogTropDePlanningLayout = new javax.swing.GroupLayout(jDialogTropDePlanning.getContentPane());
        jDialogTropDePlanning.getContentPane().setLayout(jDialogTropDePlanningLayout);
        jDialogTropDePlanningLayout.setHorizontalGroup(
            jDialogTropDePlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTropDePlanningLayout.createSequentialGroup()
                .addGroup(jDialogTropDePlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogTropDePlanningLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel12))
                    .addGroup(jDialogTropDePlanningLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton7)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jDialogTropDePlanningLayout.setVerticalGroup(
            jDialogTropDePlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogTropDePlanningLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel12)
                .addGap(50, 50, 50)
                .addComponent(jButton7)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jDialogTropDePlanning.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Festival de Cannes");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Acceuil"); // NOI18N
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        bConsulterPlanning.setText("Consulter un planning");
        bConsulterPlanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsulterPlanningActionPerformed(evt);
            }
        });

        bModifierPlanning.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bModifierPlanning.setText("Modifier un planning");
        bModifierPlanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModifierPlanningActionPerformed(evt);
            }
        });

        bCréerPlanning.setText("Créer un planning");
        bCréerPlanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCréerPlanningActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1200px-Festival_de_Cannes_Logo.svg.png"))); // NOI18N
        jLabel3.setText("    ");

        bSuppPlanning.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bSuppPlanning.setText("Supprimer un planning");
        bSuppPlanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuppPlanningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bConsulterPlanning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCréerPlanning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSuppPlanning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bModifierPlanning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(209, 209, 209)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(bCréerPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bConsulterPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bModifierPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bSuppPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Fichier");
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Quitter");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Configuration");

        jMenuItem4.setText("Dates du festival");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bModifierPlanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModifierPlanningActionPerformed
        if (Planning.countPlanning() == 0){
            jDialogPasDePlanning.setVisible(true);
        }else{
            majPlanningDispo();
            jDialogSelectionModifierPlanning.setVisible(true);
        }
    }//GEN-LAST:event_bModifierPlanningActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bConsulterPlanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsulterPlanningActionPerformed
        majPlanningDispo();
        if (Planning.countPlanning() == 0){
            jDialogPasDePlanning.setVisible(true);
        }else{
            jDialogSelectionAfficherPlanning.setVisible(true);
        }
    }//GEN-LAST:event_bConsulterPlanningActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jDialogPasDePlanning.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bCréerPlanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCréerPlanningActionPerformed
        CategorieNonPlanifié = Categories.recupCatDispo();
        majCatDispo();
        if(CategorieNonPlanifié[0][0] != null){
            jDialogSelectionCréactionPlanning.setVisible(true);
        }else{
            System.out.println("pas de planning créable car plus de categorie dispo !!"); //faire un jdialog
            jDialogTropDePlanning.setVisible(true);
        }
    }//GEN-LAST:event_bCréerPlanningActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Planning.CréerPlanning(Integer.parseInt(CategorieNonPlanifié[idCatDispoSelectionné][1]));
        jDialogSelectionCréactionPlanning.dispose();
        CréerModifierPlanningFDC.main(null, Integer.parseInt(CategorieNonPlanifié[idCatDispoSelectionné][1]),true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bSuppPlanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuppPlanningActionPerformed
        majPlanningDispo();
        if (Planning.countPlanning() == 0){
            
        }else{
            jDialogSelectionSuppPlanning.setVisible(true);
        }
        
    }//GEN-LAST:event_bSuppPlanningActionPerformed

    private void listPlanningDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPlanningDispoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPlanningDispoActionPerformed

    private void bAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnulerActionPerformed
        jDialogSelectionSuppPlanning.setVisible(false);
    }//GEN-LAST:event_bAnnulerActionPerformed

    private void bSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSupprimerActionPerformed
        Planning.suppPlanning(Integer.valueOf(tabPlanning[listPlanningDispo.getSelectedIndex()][1]));
        jDialogSelectionSuppPlanning.dispose();
    }//GEN-LAST:event_bSupprimerActionPerformed

    private void listCatDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCatDispoActionPerformed
        idCatDispoSelectionné = listCatDispo.getSelectedIndex();
    }//GEN-LAST:event_listCatDispoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listPlanningDispo_AffichageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPlanningDispo_AffichageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPlanningDispo_AffichageActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AfficherPlanningFDC.main(null,Integer.valueOf(tabPlanning[listPlanningDispo_Affichage.getSelectedIndex()][1]));
        jDialogSelectionAfficherPlanning.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void listPlanningDispo_ModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPlanningDispo_ModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPlanningDispo_ModifActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CréerModifierPlanningFDC.main(null, Integer.valueOf(tabPlanning[listPlanningDispo_Modif.getSelectedIndex()][1]), false);
        jDialogSelectionModifierPlanning.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ConfigDate.main(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jDialogTropDePlanning.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
            UIManager.setLookAndFeel( new FlatDarkLaf() );
        } catch( Exception ex ) {
            System.err.println( "Erreur d'inisialisation de LaF" );
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilFDC().setVisible(true);
            }
        });
    }
    
    
    private void majCatDispo(){
        listCatDispo.removeAllItems();
        int i = 0;
        while (CategorieNonPlanifié[i][1] != null && i < CategorieNonPlanifié.length){
            listCatDispo.addItem(CategorieNonPlanifié[i][0]);
            i++;
        }
    }
    
    private void majPlanningDispo(){
    tabPlanning = Planning.recupPlanning();
    listPlanningDispo.removeAllItems();
    listPlanningDispo_Affichage.removeAllItems();
    listPlanningDispo_Modif.removeAllItems();
    int i = 0;
    while (tabPlanning[i][1] != null && i < tabPlanning.length){
       listPlanningDispo.addItem(tabPlanning[i][0]);
       listPlanningDispo_Affichage.addItem(tabPlanning[i][0]);
       listPlanningDispo_Modif.addItem(tabPlanning[i][0]);   
       i++;
    }
}
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnuler;
    private javax.swing.JButton bConsulterPlanning;
    private javax.swing.JButton bCréerPlanning;
    private javax.swing.JButton bModifierPlanning;
    private javax.swing.JButton bSuppPlanning;
    private javax.swing.JButton bSupprimer;
    public static javax.swing.JDialog erreurDeConnexionBdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialogPasDePlanning;
    private javax.swing.JDialog jDialogSelectionAfficherPlanning;
    private javax.swing.JDialog jDialogSelectionCréactionPlanning;
    private javax.swing.JDialog jDialogSelectionModifierPlanning;
    private javax.swing.JDialog jDialogSelectionSuppPlanning;
    private javax.swing.JDialog jDialogTropDePlanning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JComboBox<String> listCatDispo;
    private javax.swing.JComboBox<String> listPlanningDispo;
    private javax.swing.JComboBox<String> listPlanningDispo_Affichage;
    private javax.swing.JComboBox<String> listPlanningDispo_Modif;
    // End of variables declaration//GEN-END:variables
}
